name: Weekly Job Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Latest Jobs
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.myjobmag.co.ke/rss"
          max_post_count: 10
          readme_path: "./index.html"
          comment_tag_name: "JOBS-LIST"
          template: "<li>🔹 <a href='$url'>$title</a></li>"
